version: '3'
services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    command: bash -c 'sleep 3 && npm start'
    volumes:
      - ./app:/app
    ports:
      - 8080:8080

  webserver:
    image: caddy:2.6
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    depends_on:
      - app
